com:
  example:
    fillAllocationAlgorithm: FIFO
    supportedSecurities:
      -
        securityId: 0
        symbol: AAPL
      - 
        securityId: 1
        symbol: GOOG
      - 
        securityId: 2
        symbol: MSFT
    